Add post about mutating webhook
ninefiveslabs/website pull request #10
Opened 2020-05-10 06:38 UTC by pawelkopka

2020-05-26 14:25 UTC, wurbanski requested changes
Chyba przydałyby się jakies nagłówki, żeby to nie była ściana tekstu :)

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +to webhooki, które można dodać w czasie runtime. Mamy dwa typy admission webhooks: walidacje (validating
```suggestion
to webhooki, które można dodać w czasie działania klastra. Mamy dwa typy admission webhooks: walidacje (validating 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +zmienić ilość replik, jeśli jest ona za mała, albo dodać dodatkowy kontener do poda(`sidecar`). Sidecarów używa się
```suggestion
zmienić ilość replik, jeśli jest ona za mała, albo dodać dodatkowy kontener do poda (`sidecar`). Sidecarów używa się
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +do monitoringu, zbierania logów czy też service meshu.
```suggestion
do monitoringu, zbierania logów czy też tworzenia service meshu. 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Przy generowaniu certifkatów pójdziemy na skróty i użyjemy skryptów z [tutoriala](https://github.com/morvencao/kube-mutating-webhook-tutorial/tree/master/deployment).
Zalinkuj może do opisu co ten skrypt robi (jest chociażby w samym skrypcie, może być link do githuba)

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Pierwsze zasoby to dość standardowy deployment oraz serwis. Do deplymentu zamontowano volumen z sekretem stworzonym
```suggestion
Pierwsze zasoby to dość standardowy deployment oraz serwis. Do deploymentu zamontowano wolumen z sekretem stworzonym
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +W odpowiedzi musimy podać wersję api(`apiVersion`), typ(`kind`) oraz odpowiedź(`response`).
```suggestion
W odpowiedzi musimy podać wersję api (`apiVersion`), typ (`kind`) oraz odpowiedź (`response`). 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Przede wszystkim podajemy typ(`patchType`) oraz naszą zmianę(`patch`).
```suggestion
Przede wszystkim podajemy typ (`patchType`) oraz naszą zmianę (`patch`). 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Wewnątrz odpowiedzi dajemy pozwolenie (`allow`) na dalsze jego przetwarzanie przez k8s wraz z uid(`uid`) odebranego requestu.
```suggestion
Wewnątrz odpowiedzi dajemy pozwolenie (`allow`) na dalsze jego przetwarzanie przez k8s wraz z uid (`uid`) odebranego requestu. 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Jak zmutować naszego poda? Jest to dość proste: w `patch` musimy podać jaką operację(`op`) chcemy wykonać,
```suggestion
Jak zmutować naszego poda? Jest to dość proste: w `patch` musimy podać jaką operację (`op`) chcemy wykonać, 
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +ścieżkę(`path`) oraz wartość(`value`). Chcemy dodać sidecar do konteneru z bazowego requestu, dlatego odczytujemy istniejącą
```suggestion
ścieżkę (`path`) oraz wartość (`value`). Chcemy dodać sidecar do konteneru z bazowego requestu, dlatego odczytujemy istniejącą
```

2020-05-26 14:25 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +0. Tworzymy certyfikaty
`0.` nie działa jako pierwszy element listy, możesz wszystkie zapisywać jako `1.`

2020-05-26 22:04 UTC, cramte requested changes

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +Ale nic bardziej mylnego, ponieważ, dzięki Dynamic Admission Control, można mutować w Kubernetesie. Przedstawię wam jak dodać sidecar za pomocą Flaska.
```suggestion
Ale nic bardziej mylnego, ponieważ dzięki Dynamic Admission Control można mutować w Kubernetesie. Przedstawię wam jak za pomocą Flaska dodać sidecar do każdego tworzonego poda.
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +czy ilość replik jest większa od minimalnej wartość. Drugi typ pozwala na zmiany requestu, który potem trafia do etcd, np. może
```suggestion
czy liczba replik jest większa od wymaganej minimalnej wartości. Drugi typ pozwala na zmiany requestu, który potem trafia do etcd, np. może 
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +zmienić ilość replik, jeśli jest ona za mała, albo dodać dodatkowy kontener do poda (`sidecar`). Sidecarów używa się
```suggestion
zmienić liczbę replik, jeśli jest ona za mała, albo utworzyć wewnątrz poda dodatkowy kontener (`sidecar`). Sidecarów używa się
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +Istnieje wiele projektów, które wykorzystują sidecary, np. [Prometheus](https://prometheus.io/), [Fluentd](https://www.fluentd.org/) czy też  [Envoy](https://www.envoyproxy.io/)
```suggestion
Istnieje wiele projektów, które wykorzystują sidecary, np. [Prometheus](https://prometheus.io/), [Fluentd](https://www.fluentd.org/) czy też [Envoy](https://www.envoyproxy.io/).
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> + - [kind](https://github.com/kubernetes-sigs/kind).
```suggestion
 - [kind](https://github.com/kubernetes-sigs/kind)
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +Przy generowaniu certifkatów pójdziemy na skróty i użyjemy skryptów z [tutoriala](https://github.com/morvencao/kube-mutating-webhook-tutorial/tree/master/deployment).
```suggestion
Przy generowaniu certyfikatów pójdziemy na skróty i użyjemy skryptów z [tutoriala](https://github.com/morvencao/kube-mutating-webhook-tutorial/tree/master/deployment).
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +Pierwsze zasoby to dość standardowy deployment oraz serwis. Do deploymentu zamontowano wolumen z sekretem stworzonym
Reszta zdania mocno po polsku, to proponuję "usługa" zamiast "serwis".

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +ścieżkę (`path`) oraz wartość (`value`). Chcemy dodać sidecar do konteneru z bazowego requestu, dlatego odczytujemy istniejącą
```suggestion
ścieżkę (`path`) oraz wartość (`value`). Chcemy dodać sidecar do kontenera z bazowego requestu, dlatego odczytujemy istniejącą
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +zawartość `request_info['request']['object']['spec']['containers']` i dodajemy naszą konfigrurację kontenera.
```suggestion
zawartość `request_info['request']['object']['spec']['containers']` i dodajemy naszą konfigurację kontenera.  
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +```bash
Ten skrypt się potem pojawia w linii 174, stąd chyba można go wywalić.

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +3. Tworzymy webook z serwisem
```suggestion
3. Tworzymy webhook z serwisem
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +A w czym może być pomocny taki sidecar? Postaram się to przedstawić w najbliższym czasie.
Tutaj bym dał jedno zdanie z wspomnianymi dwoma-trzema prostymi przykładami.

> Taki sidecar może na przykład służyć do monitorowania poda, wysyłać powiadomienia albo zapewniać service discovery. W nastepnym poście postaram się przedstawić bardziej rozbudowany przykład takiego zastosowania.

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +```bash
Ten output można skrócić o niepotrzebne pola (np. ID, Porty itp.), żeby pokazać tylko to, co istotne do przykładu.

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +admission webhook) i mutacje (mutating admission webhook). Pierwszy weryfikuje nasz requesty, np. czy są wszystkie wymagane `label`, albo
```suggestion
admission webhook) i mutacje (mutating admission webhook). Pierwszy weryfikuje nasze requesty, np. czy są wszystkie wymagane `label`, albo 
```

2020-05-26 22:04 UTC, cramte commented on content/posts/mutating_webhook.md
> +series: [breaking-kubernetes-network]
Ałtor jeszcze ^

2020-05-27 05:06 UTC, wurbanski commented on content/posts/mutating_webhook.md
> +Pierwsze zasoby to dość standardowy deployment oraz serwis. Do deploymentu zamontowano wolumen z sekretem stworzonym
W bubernetesie są serwisy a nie usługi imo 😜

2020-05-28 16:25 UTC, wurbanski approved these changes

2020-05-28 17:08 UTC, cramte approved these changes

2020-05-28 17:08 UTC, cramte commented on content/posts/mutating_webhook.md
> +A w czym może być pomocny taki sidecar? Może na przykład monitorować albo kierować ruchem sieciowy, my zaś użyjemy go symulowania awarii.
```suggestion
A w czym może być pomocny taki sidecar? Może na przykład monitorować albo kierować ruchem sieciowym, my zaś użyjemy go symulowania awarii. 
```

2020-05-28 17:08 UTC, cramte commented on content/posts/mutating_webhook.md
> +Co możesz posłużyć to testowania naszej aplikacji na różnego rodzaju fluktuacje sieciowe.
```suggestion
Co może posłużyć do testowania naszej aplikacji na wpływ różnego rodzaju fluktuacji sieciowych.
```

2020-05-28 17:13 UTC, merged