jsonnet-01-wprowadzenie
ninefiveslabs/website pull request #33
Opened 2020-06-16 23:10 UTC by wurbanski

2020-06-19 19:38 UTC, cramte requested changes

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +za tym idzie: bywa, że rozwiązania infrastruktury-jako-kodu niewiele mają wspólnego z prawdziwym kodem. Zwykle są to
```suggestion
za tym idzie, bywa, że rozwiązania infrastruktury-jako-kodu niewiele mają wspólnego z prawdziwym kodem. Zwykle są to
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +najczęściej pliki konfiguracyjne da się przedstawić w sposób równoważny jako dowolny inny rodzaj reprezentacji.
```suggestion
najczęściej pliki konfiguracyjne da się przedstawić w sposób równoważny, jako dowolny inny rodzaj reprezentacji. 
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Głównym problemem podczas zarządzania infrastrukturą przy użyciu zestawu plików tekstowych (to smutna prawda, w YAML-u
```suggestion
Głównym problemem zarządzania infrastrukturą przy użyciu zestawu plików tekstowych (to smutna prawda, w YAML-u
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +się nie programuje) jest to, jak podmienić w locie pewne dane, powtórzyć struktury czy ustalić określone wartości na
```suggestion
się nie programuje) jest to, jak podmienić w locie pewne dane, powtórzyć struktury, czy ustalić określone wartości na
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +tworzymy szablony (np. korzystając z języka szablonów w Helmie, czy jinja2 w Ansible, a bardziej hardkorowi zawodnicy
```suggestion
tworzymy szablony (np. korzystając z języka szablonów w Helmie, czy Jinja2 w Ansible, a bardziej hardkorowi zawodnicy
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +używają `sed` i `envsubst`), które na podstawie dostarczonych do nich danych, tworzą pliki tekstowe, które reprezentują
```suggestion
używają `sed` i `envsubst`), które na podstawie dostarczonych do nich danych, tworzą pliki tekstowe, reprezentujące
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +tworzymy pliki YAML bazując na odpowiednich szablonach wypełnionych danymi. Zapisując dane w pliku tekstowym musimy
```suggestion
tworzymy pliki YAML, bazując na odpowiednich szablonach wypełnionych danymi. Zapisując dane w pliku tekstowym musimy
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +zarządzaniu rozległymi, ale powtarzalnymi konfiguracjami czy definicjami.  Stworzony został jako tzw. "20% project" w
```suggestion
zarządzaniu rozległymi, ale powtarzalnymi konfiguracjami czy definicjami. Stworzony został jako tzw. "20% project" w
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +2014 r. Google, ale został ciepło przyjęty w wielu innych organizacjach i jest wykorzystywany, np. w projekcie
```suggestion
2014 r. w Google, ale został ciepło przyjęty w wielu innych organizacjach i jest wykorzystywany na przykład w projekcie
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +które wykorzystuje pewnie całkiem spora grupa administratorów. Wykorzystuje i rozszerza dobrze znaną składnię
```suggestion
których używa pewnie całkiem spora grupa administratorów. Jsonnet wykorzystuje i rozszerza dobrze znaną składnię
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Funkcjonalności obsługiwanych przez Jsonnet jest całkiem sporo i możesz je poznać korzystając z [interaktywnych
```suggestion
Funkcjonalności obsługiwanych przez Jsonnet jest całkiem sporo i możesz je poznać, korzystając z [interaktywnych
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +  kontrolę łączenia obiektów (deep merge). Jako przykład weźmy taki obiekt,
```suggestion
  kontrolę łączenia obiektów (deep merge). Jako przykład weźmy obiekt,
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +  zmieniający liczbę replik w deploymencie na Kubernetesie bez naruszania
```suggestion
  który zmienia liczbę replik w deploymencie na Kubernetesie bez naruszania
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Przykładem połączenia niektórych z tych rozwiązań niech będzie zamiana poniższego kodu (definiującego aplikacje w Spinnakerze)...
```suggestion
Przykładem połączenia niektórych z tych rozwiązań niech będzie zamiana poniższego kodu, definiującego aplikacje w Spinnakerze...
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +  namespace_patch("namespace-%03d" % i) + { spec+: {replicas: i }}
```suggestion
  namespace_patch("namespace-%03d" % i) + {spec+: {replicas: i}}
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +nadaje się on do tworzenia złożonych struktur, takich jak manifesty Kubernetesowe.
```suggestion
nadaje się on do tworzenia złożonych struktur, takich jak manifesty kubernetesowe. 
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Dostarczał on bibliotek generowanych na podstawie definicji OpenAPI (swaggera), które pozwalały na składanie plików
```suggestion
Dostarczał on bibliotek generowanych na podstawie definicji OpenAPI (Swaggera), które pozwalały na składanie z kodu plików
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +zrozumiałych dla Kubernetesa z kodu. Mimo braku dalszego rozwoju, działa na tyle dobrze, że nadal jest on wykorzystywany
```suggestion
zrozumiałych dla Kubernetesa. Mimo braku dalszego rozwoju, działa na tyle dobrze, że nadal jest on wykorzystywany
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Trzymając się jeszcze nieco tematu prometheusa i monitoringu, warto wspomnieć o projekcie
```suggestion
Trzymając się jeszcze nieco tematu Prometheusa i monitoringu, warto wspomnieć o projekcie
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +deklaratywnego opisu widoków (dashboardów) dla grafany i jest wykorzystywany przez prometheus-operatora do tworzenia
```suggestion
deklaratywnego opisu widoków (dashboardów) dla Grafany i jest wykorzystywany przez prometheus-operatora do tworzenia
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +stosowanie plików w tym formacie do definicji zasobów w Kubernetesie. Nie ma sensu chyba ukrywać, że kolejny artykuł w
```suggestion
stosowanie plików w tym formacie do definiowania zasobów w Kubernetesie. Nie ma chyba sensu ukrywać, że kolejny artykuł w
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +też tutaj linka do projektu, który współtworzę i opiera się on o wykorzystanie między innymi właśnie Jsonneta do
```suggestion
też tutaj link do współtworzonego przeze mnie projektu, który opiera się o wykorzystanie między innymi właśnie Jsonneta do
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +zarządzania konfiguracją spinnakera - [codilime/floodgate](https://github.com/codilime/floodgate). W nagraniu poniżej
```suggestion
zarządzania konfiguracją Spinnakera - [codilime/floodgate](https://github.com/codilime/floodgate). W nagraniu poniżej
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +W kolejnych postach tej serii pokażę bardziej szczegółowo jak wykorzystać narzędzie qbec do zarządzania Kubernetesem, a
```suggestion
W kolejnych postach tej serii pokażę bardziej szczegółowo, jak wykorzystać narzędzie qbec do zarządzania Kubernetesem, a
```

2020-06-19 19:38 UTC, cramte commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +także jak podejść do zarządzania zależnościami, bo jak wiadomo za kodem krok w krok podąża piekiełko zarządzania
```suggestion
także jak podejść do utrzymywania zależności, bo jak wiadomo za kodem krok w krok podąża piekiełko zarządzania
```

2020-06-19 19:42 UTC, wurbanski commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +za tym idzie: bywa, że rozwiązania infrastruktury-jako-kodu niewiele mają wspólnego z prawdziwym kodem. Zwykle są to
https://sjp.pwn.pl/poradnia/haslo/a-co-za-tym-idzie;9231.html

2020-06-19 19:51 UTC, wurbanski commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +za tym idzie: bywa, że rozwiązania infrastruktury-jako-kodu niewiele mają wspólnego z prawdziwym kodem. Zwykle są to
dam myślnik ;-)

2020-06-19 19:51 UTC, wurbanski commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +Przykładem połączenia niektórych z tych rozwiązań niech będzie zamiana poniższego kodu (definiującego aplikacje w Spinnakerze)...
przecież to kubernetes a nie spinnaker :P

2020-06-19 19:51 UTC, wurbanski commented on content/posts/jsonnet-01-wprowadzenie/index.md
> +  namespace_patch("namespace-%03d" % i) + { spec+: {replicas: i }}
jsonnet-formatter tak ustawia

2020-06-19 20:04 UTC, cramte approved these changes

2020-06-20 05:24 UTC, pawelkopka approved these changes

2020-06-20 08:55 UTC, merged